### ISSUE TITLE
Documentation for Data masking Pattern is not aligned with code

### ISSUE THREAD

**Issue by steffen-karlsson** [provectus/kafka-ui-docs#1]
### Issue submitter TODO list

- [X] I've looked up my issue in [FAQ](https://docs.kafka-ui.provectus.io/faq/common-problems)
- [X] I've searched for an already existing issues [here](https://github.com/provectus/kafka-ui/issues)
- [X] I've tried running `master`-labeled docker image and the issue still persists there
- [X] I'm running a supported version of the application which is listed [here](https://github.com/provectus/kafka-ui/blob/master/SECURITY.md)

### Describe the bug (actual behavior)

The documentation for data masking: https://docs.kafka-ui.provectus.io/configuration/data-masking are not aligned with the code. Documentation suggests to add KAFKA_CLUSTERS_0_MASKING_2_PATTERN_X to mask the data in value or key, but this is not behaving as expected.

Looking into the code: https://github.com/provectus/kafka-ui/blob/master/kafka-ui-api/src/main/java/com/provectus/kafka/ui/config/ClustersProperties.java#L137 the variable name is maskingCharsReplacement and not pattern. Thus, in order to get the masking to work, the env variable needs to be named: KAFKA_CLUSTERS_0_MASKING_2_MASKING_CHARS_REPLACEMENT_X.

### Expected behavior

Documentation and code should be aligned.
Currently, I don't think KAFKA_CLUSTERS_0_MASKING_2_MASKING_CHARS_REPLACEMENT_X is an appropriate and easy to use name.

### Your installation details

Commit hash: 56fa824

### Steps to reproduce

Running docker with the newest version of the code with following env variables:

KAFKA_CLUSTERS_0_MASKING_0_TYPE=MASK
KAFKA_CLUSTERS_0_MASKING_0_PATTERN_0=*
KAFKA_CLUSTERS_0_MASKING_0_PATTERN_1=*
KAFKA_CLUSTERS_0_MASKING_0_PATTERN_2=*
KAFKA_CLUSTERS_0_MASKING_0_PATTERN_3=*
KAFKA_CLUSTERS_0_MASKING_0_TOPICVALUESPATTERN=.*my-secret-topic.*

Not masking with **** but with the default pattern: Xxn-

**Comment by Haarolean** [comment]
Hi, thanks for reaching out.

Please note, you've linked a class that is in a private fork.

The change you've described seems to be related to changes done within https://github.com/provectus/kafka-ui/pull/3664
The documentation looks outdated indeed. Would be nice if you'd raise a PR in this repo :)

**Comment by steffen-karlsson** [comment]
> Hi, thanks for reaching out.
> 
> Please note, you've linked a class that is in a private fork.
> 
> The change you've described seems to be related to changes done within https://github.com/provectus/kafka-ui/pull/3664
> The documentation looks outdated indeed. Would be nice if you'd raise a PR in this repo :)

Sorry for the wrong linkage, I can definitely do a PR to the repo! Let me take a look at it :)

**Comment by steffen-karlsson** [comment]
I've now created a PR for documentation: https://github.com/provectus/kafka-ui-docs/pull/2
Let me know if you think the variable should be renamed for the code and then docs updated again @Haarolean

**Comment by Haarolean** [comment]
@steffen-karlsson I suggest we leave it as is, as it'd be a breaking change. Also, it's quite better to use yaml configs so it looks way better with them.

**Comment by Haarolean** [comment]
@steffen-karlsson thank you
